### ISSUE TITLE
EEG Key gets crippled

### ISSUE THREAD

**Issue by lrausch** [Open-Power-System-Data/renewable_power_plants#2]
The EEG key (Anlagenschlüssel, eeg_id) usually has 33 char.
After conversion many keys have less char.
It's not only trunkation, some key are different than then original one.

**Comment by fraukewiese** [comment]
We use data the TSO provide on http://www.netztransparenz.de/de/Anlagenstammdaten.htm Unfortunatelly, the TSO have shortened the EEG key already in the original data. This causes many problems because the plants cannot be exactly identified in the new BNetzA-register.
The partly also shorten the zip-code to three digits which reduces the possibility of getting exact geo-location.
Any hints how to solve this, welcome
Best
frauke

**Comment by fraukewiese** [comment]
By the way: At the moment the TSO get together the "Anlagenstammdaten" for 2015. During that time, they do not provide the 2014 data anymore and at the moment, there is only the 50Hertz data available. I have send them a message about this

**Comment by lrausch** [comment]
Most DSO publish the original data.
It would be hard to process all these sources.

**Comment by fraukewiese** [comment]
Oh, yes. Do you have experience with that?
